### ISSUE TITLE
Intake Information Stored Procedure

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#115]
The `registerParticipantIntake()` stored procedure has an error when inserting into the `IntakeInformation` table. Here (<https://github.com/Capping-CPCA/Database/blob/master/PROCEDURES.sql#L239>) the procedure inserts in the order:

1. `ptpMainFormSignedDate`
2. `ptpEnrollmentSignedDate`
3. `familyMembersTakingClass`
4. `familyMemberNamesTakingClass`

But, the columns in the `IntakeInformation` table are structured in the following order:

1. `otherFamilyTakingClass`
2. `familyMembersTakingClass`
3. `prpFormSignedDate`  <-- I believe that is a typo too
4. `ptpEnrollmentSignedDate`

Thus, from the mismatch in data types caused by the wrong order, I get the error:

> ERROR: column "otherfamilytakingclass" is of type boolean but expression is of type date LINE 40: ptpMainFormSig... ^ HINT: You will need to rewrite or cast the expression. QUERY: INSERT INTO IntakeInformation VALUES (newFormID, occupation, religion, handicapsOrMedication, lastYearSchool, hasDrugAbuseHist, substanceAbuseDescr, timeSeparatedFromChildren, timeSeparatedFromPartner, relationshipToOtherParent, hasParentingPartnershipHistory, hasInvolvementCPS, hasPrevInvolvmentCPS, isMandatedToTakeClass, whoMandatedClass, reasonForAttendence, safeParticipate, preventParticipate, hasAttendedOtherParenting, kindOfParentingClassTaken, victimChildAbuse, formOfChildhoodAbuse, hasHadTherapy, stillIssuesFromChildAbuse, mostImportantLikeToLearn, hasDomesticViolenceHistory, hasDiscussedDomesticViolence, hasHistoryChildAbuseOriginFam, hasHistoryViolenceNuclearFamily, ordersOfProtectionInvolved, reasonForOrdersOfProtection, hasBeenArrested, hasBeenConvicted, reasonForArrestOrConviction, hasJailPrisonRecord, offenseJailPrisonRec, currentlyOnParole, onParoleForWhatOffense, lang, ptpMainFormSignedDate, ptpEnrollmentSignedDate, familyMembersTakingClass, familyMemberNamesTakingClass, ptpConstentReleaseFormSignedDate ) CONTEXT: PL/pgSQL function registerparticipantintake(integer,date,race,sex,integer,text,text,character varying,text,states,text,text,text,text,boolean,text,text,text,text,boolean,boolean,text,boolean,text,text,text,text,boolean,text,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean,boolean,text,boolean,boolean,text,boolean,text,boolean,text,text,date,date,boolean,text,date,integer) line 62 at SQL statement

@sbohner14335 @christianmenk

**Comment by jrands** [comment]
Thanks for catching this. Looks @marcosb1 had already fixed the order in the develop branch and I just fixed the typo in 9eb4609de0f08fa96375c30d3b0b1acdcc7438b2. We should merge this to master soon.
