### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#116]
- Updates on are out of date and don't list everything updated. It would be better to put updates under wiki as the update section of the readme will differ based on what branch you are on
- People are still committing directly to the master branch
- 6 branches that have been merged but not closed
- _Insert-survey_ not merged but open and 140 commits behind

**Comment by marcosb1** [comment]
@Scott123180 Thanks for catching those discrepancies. 
As far as the `Updates`, we are planning to update those for the next release which will be done tonight `11/28/2017`. 
Committing to master branch is okay for some cases. Keep in mind this is a Database repo so we do not need to follow ALL of the same guidelines that app developers. On the other hand, this shouldn't be done in theory so we will make sure not to do that.
In regards to the branches, we do not necessarily need to close the branches after they are merged. Some branches require ongoing work, so what we end up doing is create pull requests to merge develop into those branches and continue working on the feature that the branch was opened for. 
We will make sure to check out that `insert-survey` branch. 

Thanks again.
