### ISSUE TITLE
Stored Procedure for Updating Participant Addresses

### ISSUE THREAD

**Issue by vmjoseph** [Capping-CPCA/Database#117]
Per discussion with @CBadame 
Stored procedure that can update the address info of participants

**Comment by CBadame** [comment]
- Check and update info in address table
- Check and update zipcode foreign key
- Insert new zipcode info if needed and link to field in address table

**Comment by marcosb1** [comment]
Need to wait until Release `2.0`

**Comment by CBadame** [comment]
Just completed in d69ffe6863dc3391747c95ba0d8141b41aca346f. It's been tested and currently exists in the `develop` branch. @vjoseph2 let me know if this accomplishes what you needed before we merge it to `master`.

**Comment by CBadame** [comment]
Forgot to mention the name of the procedure is `addressUpdate`. I'm working on adding it to the documentation now.

**Comment by Dr-Crow** [comment]
Merging in 2.2
