### ISSUE TITLE
Update Statements for Forms

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Database#120]
Could you guys write us update statements for all fields in our forms (for the edit feature), so this way we don't have to spend the time writing the statements ourselves and can copy and paste some code?

**Comment by jrands** [comment]
```sql
UPDATE 
SelfReferral
SET 
referralSource = newReferralSource,
hasInvolvementCPS = newHasInvolvementCPS,
hasAttendedPEP = newHasAttendedPEP,
reasonAttendingPEP = newReasonAttendingPEP,
dateFirstCall = newDateFirstCall,
returnClientCallDate = newReturnClientCallDate,
tentativeStartDate = newTentativeStartDate,
classAssignedTo = newClassAssignedTo,
introLetterMailedDate = newIntroLetterMailedDate,
Notes = newNotes;
```

Is this what you meant?

**Comment by sbohner14335** [comment]
Yes, but could you do those for the Family members, agency referrals, phone numbers, etc?

Also maybe a condition, like WHERE pID = $phpvariable

**Comment by jrands** [comment]
yep, will do, just wanted to make sure that that's what you wanted

**Comment by jrands** [comment]
Do we want people to be able to edit their own names?

What about their family members? If I remember correctly Algozzine said we wanted to see the historical data for how their family members changed from form to form so maybe that shouldn't be editable either.

**Comment by sbohner14335** [comment]
We can ask him about that on Wednesday, for now just do all of the fields in the forms.

**Comment by jrands** [comment]
created UPDATES.sql on develop branch, check out commits e155bc55a58932a5652f4304f936510fa3faef69 and 7a17f4fd856fbfa954a1f95423f6af019cc35784

**Comment by Dr-Crow** [comment]
Merging in 2.2
