### ISSUE TITLE
INSERTS.sql need to update sequences

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#122]
I am running into an issue that occurs when running the `INSERTS.sql` file. The reason is that the `curriculumid` and `classid` values are being set. For example:

```sql
INSERT INTO curricula (curriculumid, curriculumname, missnumber, df) VALUES (3, 'Cornerstone', 0, false);
```

The problem is the sequences are not being updated and thus I get unique constraint violations when the sequence is used by calling the insert statement like this:

```sql
INSERT INTO curricula (curriculumname, missnumber) VALUES ('Cornerstone', 0);
```

I believe the `INSERTS.sql` file should just use the defaults for the `id` fields and the `df` fields. This would update the sequences and remove the unique violation.

**Comment by Dr-Crow** [comment]
Jack, come on man...... <3 I'll take care of it.
