### ISSUE TITLE
Need to make sure all procedures use DF as a boolean

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#123]
I'm not sure if this occurs anywhere else in the procedures, but in the `employeeInsert()` procedure, when inserting into the employee table, the `df` is being set to `0` instead of `FALSE`.

<https://github.com/Capping-CPCA/Database/blob/master/PROCEDURES.sql#L325>

```sql
INSERT INTO Employees
VALUES (personID, em, pPhone, pLevel, 0);
```

I'd check to make sure other procedures don't try to reference `df` as an `INT` instead of a `BOOLEAN`.

**Comment by Dr-Crow** [comment]
Sorry for all the bugs, this should of been taken care off. Our bad. @CBadame can you look into this looks like a simple fix.
