### ISSUE TITLE
Stored Procedure Errors

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#128]
- peopleInsert
```SQL
SELECT peopleinsert( fname := "michael"::text, lname := "llama"::text, mInit := "a"::varchar(1) );
```
before it let me do the insert without an empty string, but also with a middle init I'm getting an error 

`[2017-11-30 10:45:59] [42703] ERROR: column "michael" does not exist`
`[2017-11-30 10:45:59] Position: 31`

- createOutOfHouseParticipant
I created a new person and gave them an ID of 18, then ran
```SQL
SELECT createOutOfHouseParticipant( outOfHouseParticipantId := 18::int, participantAge := 11::int, participantRace := 'Caucasian'::race, eID := 1::int );
```
`[2017-11-30 10:52:57] [2F005] ERROR: control reached end of function without RETURN`
`[2017-11-30 10:52:57] Where: PL/pgSQL function createoutofhouseparticipant(integer,integer,race,sex,text,integer)`

**Comment by jrands** [comment]
- for peopleInsert, we are now enforcing a single varchar instead of text. That is why it can't take in an empty string. If you're not entering in an initial, please just enter NULL.

looking into createOutOfHouseParticipant now

**Comment by Scott123180** [comment]
@jrands ik about the single character. I got the error message above if you include the single character. Should have clarified, that's my b

**Comment by jrands** [comment]
- use single quotes when submitting text fields

- createoutofhouseparticipant is submitting properly, that's not really an error message so don't worry about it. It's expecting a return type from a previous version that returned a formID. Will make it return VOID for release 2.2.
b044453a05793fab29b5f95fabfd89f7782f8227

**Comment by Dr-Crow** [comment]
@Scott123180 Also for createoutofhouseparticipant, you are not entering sex. Why is that?

**Comment by Scott123180** [comment]
good question

**Comment by Dr-Crow** [comment]
Merging in 2.2
