### ISSUE TITLE
Insert Survey

### ISSUE THREAD

**Issue by CBadame** [Capping-CPCA/Database#13]
Tasks:
1. Find `participantID`
2. Create a `Form`
4. Get `ClassOffering`
5. Insert data

**Comment by marcosb1** [comment]
continue off of #50

**Comment by Dr-Crow** [comment]
Inserting surveys and inserting attendance will drive the creation of class offerings. So when designing this please take that into account.

**Comment by marcosb1** [comment]
resolved in d118f2a064cd99c2584ebbbd710d78305f8fc000
