### ISSUE TITLE
Syntax Error in RegisterParticipantIntake

### ISSUE THREAD

**Issue by michelleburd** [Capping-CPCA/Database#132]
Currently I am getting an error when submitting an Intake Packet: 

> ERROR: argument of AND must be type boolean, not type race LINE 2: SET Participants.race = intakeParticipantRace AN... ^ QUERY: UPDATE Participants SET Participants.race = intakeParticipantRace AND Participants.sex = intakeParticipantSex WHERE Participants.participantID = pID CONTEXT: PL/pgSQL function registerparticipantintake(integer,date,race,sex,integer,text,text,character varying,text,states,text,text,text,text,boolean,text,text,text,text,boolean,boolean,text,boolean,text,text,text,text,boolean,text,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean,boolean,text,boolean,boolean,text,boolean,text,boolean,text,text,date,date,boolean,text,date,integer) line 35 at SQL statement"

This is because in the piece of the Procedure that checks if the person is in the system, the UPDATE statement attempts to set the participant data using 'AND' rather than a comma separated list. 

`UPDATE Participants
    SET Participants.race = intakeParticipantRace AND
    Participants.sex = intakeParticipantSex
    WHERE Participants.participantID = pID;`

Should be:

`UPDATE Participants
    SET Participants.race = intakeParticipantRace,
    Participants.sex = intakeParticipantSex
    WHERE Participants.participantID = pID;`

**Comment by sbohner14335** [comment]
Also the reason mandated field is not included in the stored procedure. My fault for not realizing that earlier. If you can add it in when you fix this issue that would be perfect and I'll just update my code.

@Jesse-Opitz is aware of this

**Comment by Vesiix** [comment]
@michellecrawley fix is implemented in branch issue138 waiting for a pull request and I'm still fixing Steven's comment. Will be pushed after everything's fixed.
