### ISSUE TITLE
public."People" vs. public."people"

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#16]
There are currently two people tables in the database. `People` and `people`. Not sure which one is supposed to be the actual table.

**Comment by Dr-Crow** [comment]
Thanks @blackjack26  for point this out.  **public."People"** has been dropped.  Please note if you are not using **public.** then People and people point to the same table. For example:

Select * from people; and Select * from People; give you the same results.

But Select * from public."People" and Select * from public."people" do not.
