### ISSUE TITLE
Archive capabilities

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#18]
Currently we cannot archive any information. The only way to remove data is to completely delete it. 

I would suggest possibly a `df` (delete flag) column in the tables that we want to be able to archive the data. This way we can "delete" it by setting the `df` value to `1`. Then we can "restore" the data later if needed by setting `df` back to `0`.

Each of our queries can always just look for rows with `df = 0` unless we want to see archived data.

**Comment by CBadame** [comment]
While adding the ability to archive could be beneficial, we do not believe that this would be the best way to implement it. For now, users have the ability to make dumps or snapshots of the DB if need be. We will continue to discuss other options in the meantime.

**Comment by blackjack26** [comment]
The only reason I mention this is because @algozine mentioned that he doesn't want anything to actually be deleted.

**Comment by CBadame** [comment]
We still plan on adding the functionality, but are currently discussing the best means of doing so.

**Comment by Dr-Crow** [comment]
Location, Classes, and Curricula.

**Comment by Dr-Crow** [comment]
This class is part of curriculum, can't be archived.

**Comment by Dr-Crow** [comment]
Look into good ways to take snap shots of the db to integrate with the CPCA backup system. Doing a DB dump is going to be huge after awhile.

**Comment by Dr-Crow** [comment]
https://www.postgresql.org/docs/9.0/static/backup-dump.html

https://support.solarwinds.com/Success_Center/Web_Help_Desk_(WHD)/Back_up_and_restore_the_PostgreSQL_database_using_the_command_line

Both the official PostgreSQL docs and Solar Winds says to use pg_dump and pg_restore. I think we should have a schedule backup, maybe ever night? We need to talk about Christina about rotation of the backups, maybe every month? We can always compress the files to minimize the size, unlike trying to back up the PostgreSQL file tree.

**Comment by blackjack26** [comment]
I'm not sure exactly what a backup is going to do to "archive" a class or curricula unless every time some one clicks the delete button, a backup is made and then the row is deleted from the table.

**Comment by marcosb1** [comment]
@Dr-Crow where did we land on this?

**Comment by Dr-Crow** [comment]
We are adding a DF flag to the tables. I talked with @jrands , idk if he is working on it or do you want to take it.

**Comment by CBadame** [comment]
@Dr-Crow John's knocking it out right now. GG

**Comment by jrands** [comment]
@Dr-Crow which tables do we want to archive? You say Location Classes and Curricula but Location no longer exists. Sites?

**Comment by Dr-Crow** [comment]
![image](https://user-images.githubusercontent.com/9339757/32083424-59a7e256-ba90-11e7-8f76-2585833e553f.png)

I think we need to worry about these tables. But I am a little confused. We need a df flag in sites, class, and curricula. But i am not sure about the relations in between. 

@blackjack26 Can you provide some more detail on what actually happens  when they delete it? Like for curriculum if they delete that does it delete all the classes under that? Or?

**Comment by blackjack26** [comment]
So we could put delete flags in `CurriculumClasses` and `ClassOffering` but it really would only serve the purpose of saying "this is an old connection". The archive is more to just keep the display update to date with current classes and curricula. We also still need the old curricula and classes for reports and participant data. So really I think it would suffice to just do the delete flag on curricula, sites, and classes. The only case that the connection tables would need the delete flag would be if a query didn't check those base tables for the delete flag.

I'm not sure if that makes any sense or helps, but I think that's the basic idea.
