### ISSUE TITLE
ENUM Checks

### ISSUE THREAD

**Issue by Dr-Crow** [Capping-CPCA/Database#21]
@blackjack26 could you and the Web team look over our ENUMs and make sure we have all the values you want. For instance on RELATIONSHIP, we grabbed all the values off of facebooks UI, but don't know if those are the values that the UI team wants. We just want to make sure the UI team doesn't need different values then we have now. We still need to create a some ENUM types as you can see in #15 . Feel free to tag/assignee people from your the UI team to this issue.

**Comment by blackjack26** [comment]
@vjoseph2  @michellecrawley

**Comment by blackjack26** [comment]
The `curriculumtype` is currently just **FULL** and **MINI**. Are these the only two curriculum types? Also, none of the curricula in the database currently use either one of these ENUMs.

**Comment by Dr-Crow** [comment]
The type has been dropped. Thanks for letting us know it is still in there. If you see anything else hanging around let us know. Also you can always refer to the latest CPCA.sql file on github for what tables/types/views/etc should be there.

**Comment by blackjack26** [comment]
I also see `sitetype` which I think has been replaced with `programtype`.

**Comment by Dr-Crow** [comment]
I just delete form type as well.

**Comment by Dr-Crow** [comment]
@evanmena

**Comment by ghost** [comment]
@Dr-Crow The races detailed in the Monthly report are: 

Caucasian, African American, Multi Racial, Latino, Pacific Islander, Native American, Other

**Comment by blackjack26** [comment]
There should be a `coordinator` permission added to the `PERMISSION` enum.
