### ISSUE TITLE
Directory For Storing files displayed in the DB wiki

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#22]
To upload files or pictures to the wiki, you need a URL where the file is stored. Need a bin to hold these files and display them in the wiki.

**Comment by Dr-Crow** [comment]
If you must have pictures, please submit another pull request with the images in their own folder under the doc folder.

/doc/phpstorm/images.......

**Comment by Scott123180** [comment]
Yes I planned on adding pictures to help explain it. Now that I know where I should put the files I won't make more work for you guys. I'll just create the directory and put the files in it.
