### ISSUE TITLE
"Sex" field missing from Participants table

### ISSUE THREAD

**Issue by jrands** [Capping-CPCA/Database#25]
@colby-gray brought this up, since it is on the attendance sheet all participants, including those in the jails have their sex recorded so we should add this field to the Participants table.

**Comment by CBadame** [comment]
There is a "sex" field in the "FamilyMembers" table, which is linked to every participant. This may already be accomplishing what we need, although it is not the most direct relationship.

**Comment by Dr-Crow** [comment]
Good spot, we need to add that to Participants.

**Comment by jrands** [comment]
resolved in <62f7a18>
