### ISSUE TITLE
Connecting to the database, How-to

### ISSUE THREAD

**Issue by ghost** [Capping-CPCA/Database#26]
I made a little infographic image of how to connect to the database using pgadmin and psql on the command line. I've never used them before so I figured it might be helpful to some one. Ignore the color scheme change halfway through.

Tried to open a branch and submit a PR but it appears I'm not allowed to, so this issue will have to do.

Attached the .png here.

![connectinginfographic](https://user-images.githubusercontent.com/31941008/30993041-f1e543e6-a47a-11e7-8a71-a67151e01923.png)

**Comment by jrands** [comment]
Thanks Evan, this is very helpful. I went ahead and added it to the docs folder.
