### ISSUE TITLE
Stored Procedure Request

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#27]
Just need a couple of stored procedures to replace these hard-coded queries when you get a chance. Thanks :smiley: 

1. Get all curricula in alphabetical order:
``` sql
SELECT c.curriculumid, c.curriculumname FROM curricula c ORDER BY c.curriculumname ASC;
```
2. Get all classes and their curriculum id's
``` sql
SELECT cc.curriculumid, cc.topicname from curriculumclasses cc ORDER BY cc.curriculumid;
```

**Comment by jrands** [comment]
Hi @Scott123180, added these as views in 2cb0e042b929a3043cbe547118eaebbe3622a2a8
