### ISSUE TITLE
Remove "PARENTINGPROGRAM" Type

### ISSUE THREAD

**Issue by jrands** [Capping-CPCA/Database#30]
Since this is a PEP only application, the "PARENTINGPROGRAM" enumerated type is no longer used and not needed.

**Comment by CBadame** [comment]
parentingProgram has been removed from CPCA.sql, StoredProcedures.sql, and SampleData.sql. Everything in the live db has been updated with the exceptions of the facilitatorInsert function and the removal of the parentingProgram type itself, which cannot be done until #42 is resolved.

**Comment by CBadame** [comment]
@Dr-Crow I'm only adding you to this as it should be resolved once the db is resourced.
