### ISSUE TITLE
Database Typos

### ISSUE THREAD

**Issue by CBadame** [Capping-CPCA/Database#32]
- "hasAgencyConstentForm" should be "has AgencyConsentForm"
- "addtionalInfo" should be "additionalInfo"
- "hasInvolvmentCPS" should be "hasInvolvementCPS"
-  "hasMentalHeath" should be "hasMentalHealth"
-  "childrenLiveWithIndivdual" should be "childrenLiveWithIndividual"

**Comment by jrands** [comment]
b1bfcff68380012782032d30c8bf4241e3f1bbee
