### ISSUE TITLE
ENUM types for Selects (or more specifically options)

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Database#33]
We would like if you guys could write us some queries that return all of the ENUM types for our <select> fields in our form. This would relieve us of updating our code (html) every time a new ENUM type is added to the database.

**Comment by jrands** [comment]
Hi @sbohner14335 , 

Here's a simple query you can call to accomplish this that will return a specific type in an array: 

`SELECT enum_range(NULL::relationship);`

Where "relationship" is the name of the type you want. If you want a separate record for each item: 

`SELECT unnest(enum_range(NULL::relationship))  `

If it would be beneficial for you to have this in a view we can do that, but the queries are small enough where I don't think you'll need one.

-John

**Comment by sbohner14335** [comment]
Sweet, that's all I really need. No views are needed

- Steve
