### ISSUE TITLE
Database user table

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#35]
## High Priority

This might require web app and DB Team to work together but I need to display information about the specific user who is logged in (i.e. a query showing the titles of the last 20 classes that an employee taught). I know we're using the LDAP stuff and still possibly needing a DB table for username and password?

Thanks for your help!

**Comment by blackjack26** [comment]
So with the LDAP login I am storing a session variables `$_SESSION['employeeid']`. You can use this to connect the currently logged in user with the database.

So for now, set a dummy variable in login, like  `$_SESSION['employeeid'] = 3`, for now until the LDAP stuff is merged.

**Comment by Scott123180** [comment]
Great thanks!
