### ISSUE TITLE
ER Diagram Updating

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#36]
.png of ER diagram under `/docs` has the Children table spelled as `Childern` instead of `Children` in 3 places (pk/fk, title of table, and note about memberid = childrenID)

also can you update the lucidchart view on the readme.MD to have the new ER diagram instead of the old

thanks a million!

**Comment by jrands** [comment]
fd12769b7c4476d421601f99dc11ef51498e1263
