### ISSUE TITLE
New DB Server for Testing

### ISSUE THREAD

**Issue by dtoverington** [Capping-CPCA/Database#40]
We would like a new server created with a copy of the DB to connect to the two testing servers. This DB should only be updated once a week on Wednesdays around 9pm to match the deployment schedule of the app itself.

**Comment by Dr-Crow** [comment]
Perfect, I needed to redeploy the database on Windows 2008 anyways!

**Comment by k6789j** [comment]
Why is that being referenced here?  All we want is a clone of the database on a separate server for testing

**Comment by dtoverington** [comment]
Is there an ETA for getting this server running? We really need a static instance of the DB for the test systems to make sure everything stays consistent per Algozzine's request

**Comment by CBadame** [comment]
Yea, Jimmy was planning on having it up tonight when he resources the current database mentioned in #42.
