### ISSUE TITLE
"New" added to permission ENUM

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#41]
In relation to the conversation about LDAP, add a permission to the permissions enum named `"New"`. This is for user's who are newly created but not assigned a real permission. It'll be the default so in the `employeeInsert` procedure, use this "New" role as the default.

**Comment by Dr-Crow** [comment]
Jack, I just wanted to make sure these are the permissions levels your need.

'New', 'Coordinator', 'Facilitator', 'Administrator'

Is Administrator needed? For permission levels, these should just be people who are employees and have LDAP entries.  I removed Superuser, since they are in their own table.

**Comment by blackjack26** [comment]
Currently I know we want to use 'New', 'Coordinator', 'Facilitator', 'Administrator', and 'Superuser'. But I know there was talk of having a separate login for the Superuser. And if that doesn't require the database, then the ones you have listed should be sufficient.

**Comment by Dr-Crow** [comment]
Right, now Superuser is not connected to any of our tables. Its just a standalone table with username, hashed password and salt. I think a separate login would be a good idea, unless you can do some fancy voodoo on the normal login screen to handle superusers.  

What does the Administrator permission level allow people to do? Will that ever be a non CPCA employee?

**Comment by blackjack26** [comment]
Yeah I could make the login screen work for both super users and LDAP users. The Administrator would be someone like Gwen who can edit participants, classes, curricula, etc. I don't think anyone outside of the CPCA would be an Administrator. The only one I can think of is Algozzine who would be the Superuser.

**Comment by blackjack26** [comment]
Also, what is the name of the standalone table with the user name and password? I don't see it in the database,

**Comment by CBadame** [comment]
It's not currently in the live db, but we have it in the SQL creation code, along with the insertion of Algozzine to the table. It should be up and running after Jimmy resources the db tonight.

**Comment by Dr-Crow** [comment]
Sorry, was at work. The table is Superusers and it will be in the database tonight after we get things deployed on Windows 2008 R2.
