### ISSUE TITLE
View or Stored procedure request

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#44]
Tried writing a little bit of it for you guys but it's a pretty complex query.

English version: provide the first, last, DOB, zip, numchildren(from the very last class each participant attended in the table 'participantclassattendance') of all of the participants in a given `curriculumname` (_input into proc_) with a given `facilitatorid` (_input into proc_) who have shown up in the past 3 weeks (of that given curricula and facilitator) and who hasn't completed the curricula (hasn't failed out/quit/gone to prison and who have completed all but two or less classes of that specific curriculum).

Some SQL to help but I got a little stumped and it was taking too much time
```SQL
/* display class attendance */

select
  people.firstname,
  people.lastname,
  participants.dateofbirth,
  forms.addressid,
  participantclassattendance.numchildren

from
  classes,
  curricula,
  facilitatorclassattendance,
  classoffering,
  participantclassattendance,
  participants,
  people,

  /* zip code related */
  participantsformdetails,
  forms,
  addresses

/* general linking */
where  people.peopleid = participants.participantid
and    participants.participantid = participantclassattendance.participantid
and    participantclassattendance.date = classoffering.date
and    participantclassattendance.sitename = classoffering.sitename
and    classoffering.topicname = facilitatorclassattendance.topicname
and    classoffering.sitename = facilitatorclassattendance.sitename
and    classoffering.topicname = classes.topicname
and    classoffering.curriculumid = curricula.curriculumid

/* zip code linking */
and participants.participantid = participantsformdetails.participantid
and participantsformdetails.formid = forms.formid
and forms.formid = addresses.addressid

/* class specific information */
--and  cirriculum is "Women's DC Jail"
and    facilitatorclassattendance.facilitatorid = 5;
```

Thanks :smile:

**Comment by jrands** [comment]
Hi Scott, a few things:

1) As nothing is being inserted here, I think a view would be better suited for this query. I added the following as a view named attendanceinfo into the database

```
SELECT
  people.firstname,
  people.lastname,
  participants.dateofbirth,
  participants.race,
  participants.sex,
  participantclassattendance.numchildren,
  addresses.zipcode
FROM
  people, participants, addresses, participantsformdetails, participantclassattendance, facilitatorclassattendance, forms, curricula, classes, classoffering
WHERE 
  people.peopleid = participants.participantid
  AND participants.participantid = participantclassattendance.participantid
  AND participantclassattendance.sitename = classoffering.sitename
  AND classoffering.topicname = facilitatorclassattendance.topicname
  AND classoffering.sitename = facilitatorclassattendance.sitename
  AND classoffering.topicname = classes.topicname
  AND classoffering.curriculumid = curricula.curriculumid
  AND participants.participantid = participantsformdetails.participantid
  AND participantsformdetails.formid = forms.formid
  AND forms.formid = addresses.addressid;
```


2) There is an issue with this. Looking at this made me realize that it might be a problem retrieving zip codes from jail participants who do not have any forms filled out, as the only way to retrieve zipcode is through the forms table.  @marcosb1 is this right?

**Comment by Scott123180** [comment]
Heyo,

Thanks for response.

I don't think that the view above creates the right response. Attendance needs to select on the curriculum name of the course given and there aren't any fields to do that. I also need to select on classes in that curriculum taught by that facilitator which can be done by subtracting dates in postgres ([link](https://wiki.postgresql.org/wiki/Working_with_Dates_and_Times_in_PostgreSQL))

The view that needs to be created may need a few nested queries to work right. In general, I just need the roster of anyone in any of the last 3 weeks of class that the employee/facilitator has taught within a specific curriculum. That person also shouldn't have quit, finished, or left the program (refer to first comment). I think the structure may need to be changed a bit so that the cirriculumID of the class is also in other tables but I'll leave that decision up to you guys.

Yeah we may need to have a default zip code or something. I think anyone in jail gets a default zip code of 12601 as of now, so maybe that might be a good one to enter by default? If a person doesn't have any forms filled out I think the plan is to create default forms for them.

Also to allow SQL syntax highlighting just surround the code with '```SQL' (the dashes are on the tilde key) and the same 3 dashes at the end.

_EDIT: also if you can order alphabetically A-Z. Thanks_

**Comment by Scott123180** [comment]
_EDIT 2: can you also return the id of each person?_

**Comment by jrands** [comment]
Hi Scott, sorry for the delay with this. We have modified the classattendancedetails view and I am confident it will serve the purposes you need. Please check out the views file or 00362196f556dee5261ccaa836774614ef234177. It has all the columns that you need and we believe it solves this issue. An example call would look like:

```SQL
select * from classattendancedetails where curriculumname = 'Meadow Run' AND facilitatorid = '1';
````

class date is included so you can limit by the last 3 weeks on your end.

Please let us know if you have any further questions.

**Comment by Scott123180** [comment]
Can you add _zip_ to this view?
