### ISSUE TITLE
Stored Procedure Request

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#45]
Hi DB team,

can you write a stored procedure for a new person in the database? This is for jail people who may not have intake packets and need their information stored in the system for classes.

Input is:
- first name
- last name
- middle initial
- sex
- race
- age
- number of children under 18
- Zip code.

Thanks again!

**Comment by Scott123180** [comment]
_Edit: I guess it's more of a function, but can you have it return the new person's ID after they are added?_

**Comment by marcosb1** [comment]
Note that to create an outOfHouse participant you don't need `number of children under 18` and `zip code`. This is how the database is set up so make sure there are no conflicts with the font end. Otherwise we now have a proc that will solve this problem. Duplicate #56
