### ISSUE TITLE
Stored Procedure Request -- Change age

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#46]
Need a stored proc to change age of participant. If a participant doesn't have a specific birthday (likely because he/she is in jail) then age can change and so needs to be updated.

Thanks :smile:

**Comment by Dr-Crow** [comment]
For people who we only can get there ages by guessing/asking, we are making up a default birthday. There is no reason to change the age. If there is then you can change it manually, this does not need to be a stored procedure.
