### ISSUE TITLE
Class Attendance Insertion

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#49]
Last major proc for attendance. Can you please make a stored procedure for submitting a new class offering along with a list of participants for the class.

You guys are the best :1st_place_medal:

**Comment by Scott123180** [comment]
_Edit: age is going to be a number so in the proc can you make it subtract that number of years from today's date? Thanks_

**Comment by marcosb1** [comment]
closed see [this](https://github.com/Capping-CPCA/Database/blob/participant_info_proc/doc/users/UsingStoredProcedures.md) for instructions on how to use the attendance procedure

**Comment by marcosb1** [comment]
Need to re-examine the use-case for offsite attendance insertions

**Comment by Scott123180** [comment]
By offsite you mean prison, right? If so, off-site should work just fine with the function that you wrote for that before. If a participant is offsite, they will be inserted into the DB as a person right before we submit the class attendance. Thanks to your function we'll have their ID before we try to submit a class. This proc just needs to take the fields given to it and make an entry into the classoffering table.

**Comment by marcosb1** [comment]
@Scott123180 offsite = (prison || rehab)

I'm thinking about creating a new parameter that will be a flag that determines whether the participant being inserted is for In-house or out-of-house. This way, we can create new participants for out-of-house attendance sheets, but not for in-house attendance sheets.

Theoretically, a participant should only be dynamically created if they are new to an out-of-house class. If they are an in-house class, they need to fill out a referral and intake before attending the class.

**Comment by Scott123180** [comment]
@marcosb1 
I don't think the PHP/web-app needs that functionality. Regardless of whether or not a person is inhouse/out of house, the logic for that is handled in the PHP.

I'm not sure if the offline application needs that functionality, but I think the procs for those will be very different because the offline app doesn't have access to the same amount of information as the WebApp does.

**Comment by marcosb1** [comment]
resolved in 33dc344

**Comment by Scott123180** [comment]
thanks!
