### ISSUE TITLE
Procedure Error

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#52]
@CBadame 
`ERROR:  column facilitators.program does not exist
LINE 83:     facilitators.program`

https://github.com/Capping-CPCA/Database/blob/a86a404bf05e9c10f6b4f6d5b078a069cbfce12d/VIEWS.sql#L83

Table definition -
https://github.com/Capping-CPCA/Database/blob/a86a404bf05e9c10f6b4f6d5b078a069cbfce12d/TABLES.sql#L130-L138

**Comment by Dr-Crow** [comment]
@CBadame  he is the author of the view

**Comment by Scott123180** [comment]
yeah just changed my b

**Comment by CBadame** [comment]
This is a known issue. #42 is preventing us from updating the view in any way, but should be resolved when @Dr-Crow redeploys the sql later tonight.

**Comment by Scott123180** [comment]
I deployed a new instance of the DB on your server under `test_new_DB` and added some data I needed for testing and that seems to be working without an issue (I removed the field that was causing the issue).

_code for the view just needs to be updated if you're getting rid of the field_
