### ISSUE TITLE
Author Is John

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#57]
referencing #27 , John created these for me so you can update the author for those two views :+1: 

https://github.com/Capping-CPCA/Database/blob/a05426edc98db6c7302da2eaa3aa5e0a5e570ad1/VIEWS.sql#L152

https://github.com/Capping-CPCA/Database/blob/a05426edc98db6c7302da2eaa3aa5e0a5e570ad1/VIEWS.sql#L162

**Comment by CBadame** [comment]
Done
