### ISSUE TITLE
Delete Flag in Facilitators and Employees Table

### ISSUE THREAD

**Issue by michelleburd** [Capping-CPCA/Database#59]
We need a delete flag in order to archive employees so that they are excluded from the UI. We also need one in the Facilitators table for situations such as when a Facilitator changes to a Coordinator.

So, the Facilitators and Employees tables both need a DF.

References #18

**Comment by jrands** [comment]
got it, will update live DB when I get home later unless someone else does it before me. 
f66bcba6ed323a833b192f5d3c9c04378a2d1ca5
