### ISSUE TITLE
proc for createFacilitatorClassAttendance

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#73]
need asap please

**Comment by Scott123180** [comment]
Anyone know if the regular app will be allowed to run insert statements? If we're allowing it then I can just use an insert statement and close the issue.

**Comment by CBadame** [comment]
By regular app, do you mean the WebApp?

**Comment by blackjack26** [comment]
@Scott123180  I run insert statements all the time. You don't need a procedure for everything. Just make sure to sanitize the input.
