### ISSUE TITLE
Add Self Referral Function Issue

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#77]
In the `addSelfReferral()` function, there is a clear copy-paste error with `intakeParticipantID` on line 858 of `PROCEDURES.sql`. The line states:

```sql
WHERE Forms.participantID = intakeParticipantID;
```

but should be 

```sql
WHERE Forms.participantID = referralParticipantID;
```

Also the function definition has `referralParticipantID INT DEFAULT NULL::INT,` but the default cannot be NULL because the table definition for `participants` has `participantId NOT NULL` and doesn't use an autoincrement.

**Comment by Dr-Crow** [comment]
Thank you Jack!
