### ISSUE TITLE
Locations ENUM (programtype)

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#78]
The old `sites` table has been replaced with simply just using the `programtype` enum. I'm fairly sure we still wanted to be able to add more program types if one were to come along in the future. As of right now the only way to do that would be to change the `programtype` enum. The user cannot currently add a program type through the application.

I've removed my locations pages because the sites table doesn't exist anymore. If we are able to add new programs, there should probably be a sites table to track the values that are currently in the enum. Instead of referencing the `programtype` enum, it would reference the sites table. 

I'm also not sure if this is even something that needs to be done since the enum may only be updated every 10 years.

@algozine

**Comment by Dr-Crow** [comment]
So, ideally you would like an way to expand and "mange" the enums for programtype? Just want to be on the same page, so I can see if you can modify enums without causing to much trouble to the db. If not we can switch to TEXT or something but that might cause issues with reporting down the line.

**Comment by blackjack26** [comment]
Yes. It was a table before that we could add/delete from but as an enum there is no real way to edit it easily.

**Comment by Dr-Crow** [comment]
And for the most part, you would not want to edit it, you want to just add to it. Bc then if you delete it you would loose historical data?

**Comment by blackjack26** [comment]
Correct, if they do need to delete it they are met with several warnings and probably only a superuser could delete it.

**Comment by Dr-Crow** [comment]
@blackjack26 So with the site table now back, will you want a way to edit the siteType,  jail, rehab, in house?

**Comment by Dr-Crow** [comment]
Sorry did not see #83. I am going to close this out.
