### ISSUE TITLE
Intake Packet Stored Procedure

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Database#79]
The intake packet does not ask for a participant's race or sex (just ethnicity, which you guys already have), so those fields probably shouldn't be in the intake stored procedure.

Also, there are no fields that check if it is okay to leave a message for a given phone number in the procedure. Not sure how you guys want to handle that, but just letting you know that we have those fields in our form (as checkboxes off of each phone number). If you guys want to ask Algozzine or Gwen whether if it's okay or not to remove that is up to you. 

![intake](https://user-images.githubusercontent.com/8646088/32479419-c2f96ea8-c357-11e7-9ff9-dfebe9be4d5f.png)

Either way is fine with me!

**Comment by sbohner14335** [comment]
Just spoke with Algozzine about race and sex.

He said the Ethnicity field should be Race (as in the ENUM), so i've changed it on my end.

**Comment by jrands** [comment]
removed ethnicity in 8125c45bb81e423fd4ba39a2f14548ea0757d4a3, please store that value in intakeParticipantRace instead

**Comment by sbohner14335** [comment]
Also, could you guys modify the intake stored procedure so that it returns the form ID. I need that ID for the createFamilyMember procedure, as you guys require that field.

**Comment by jrands** [comment]
sorry, can't believe i forgot that, fixed in 5efae946554a7257c6c527733fe1d37a8020a347

idk about the leave a message checkboxes for now, i'll talk to the team about it

**Comment by jrands** [comment]
-has jail/prison record should be one field
8a41b62a8517e07ad94ad3a9db1700b8584fce1b
-language needs to be added
4ce9d42f99ca19ea18d7f632355494a535954b81
-family members taking classes and their names
???

**Comment by marcosb1** [comment]
@jrands we did this in ed3acda1c1f1717fb9bddc346730a16889853313 right?

**Comment by sbohner14335** [comment]
Leave message fields for phone numbers (low priority)

**Comment by jrands** [comment]
everything listed in this issue has been implemented and is working
