### ISSUE TITLE
Zip Codes

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#80]
I noticed this when reviewing the referral forms pull request:

- Zip codes should not be stored as an `INT`, they should be a `VARCHAR(5) ` or possibly `VARCHAR(10)` if we are including zip codes +4
    - Ex: my zip code is **02871**, storing this as an `INT` loses the 0, thus when loaded it'll display **2871**

**Comment by Dr-Crow** [comment]
Thanks for the heads up. Thanks a big issue. I think we might go with varchar(5) since they don't seem to use the extended zip codes on reports.

**Comment by jrands** [comment]
We could do this with phone number as well. Make it a ```varchar(14)``` instead of ```TEXT```.

**Comment by Dr-Crow** [comment]
Phones numbers are find, leading zeros won't disappear. Changed it in latest push.
