### ISSUE TITLE
Self Referral Stored Procedure Error

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#81]
In `PROCEDURES.sql` line **861** (https://github.com/Capping-CPCA/Database/blob/master/PROCEDURES.sql#L861) there is another copy-paste error with `agencyReferralParticipantID`. It should be `referralParticipantID`.

@jrands

**Comment by jrands** [comment]
Thanks, fixed in a449397a1698fb3435f569378ff79a5a8098875c
