### ISSUE TITLE
Notes for participants

### ISSUE THREAD

**Issue by marcosb1** [Capping-CPCA/Database#82]
Create a notes table containing on a ONE-TO-MANY from PARTICIPANTS to a NOTES table, containing: 
- Participant ID
- Note Content
- Date Taken
- Employee ID

**Comment by algozine** [comment]
would love to see the database updates required for this implemented this week ... don't want to have anything delaying Elijah in the work he's going to deliver... thanks

**Comment by jrands** [comment]
this has been completed in commit 45a75c50aaa9c951fd6e5c771e7b465815d6e5f8

**Comment by CBadame** [comment]
The necessary changes have already been added to the creation SQL and pushed to the TABLES.sql file on this repo. They are currently available to anyone running a local instance of the db, and will be added to the 10.11.12.34 database during the next resourcing
