### ISSUE TITLE
SiteType Enum Stored Procedures

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Database#83]
Create stored procedures for:

- Adding to the `siteType` enum
- Removing from the `siteType` enum

**Comment by CBadame** [comment]
After a little bit of testing, it looks like each of these can be done with a single line of SQL:
```sql
ALTER TYPE programType ADD VALUE 'valueName';
```

and

```sql
DELETE FROM pg_enum WHERE enumtypid = 'programType'::regtype AND enumlabel = 'valueName';
```

I double checked the oid's after adding and removing values just to ensure that we wouldn't run into the same issue as last time, and everything seemed to add up. Is there anything else that might be needed regarding this?

**Comment by blackjack26** [comment]
The queries work and @marcosb1 added something in the wiki for it.

**Comment by CBadame** [comment]
Alright cool, just saw that.
