### ISSUE TITLE
Add address foreign key to Sites table

### ISSUE THREAD

**Issue by marcosb1** [Capping-CPCA/Database#91]

**Comment by algozine** [comment]
So, was the "address" of the site (or location) going to be a key?  I had originally laid down the requirement as having an actual address (like street, city, zip) be available for entry from the UI into the DB, but not required.

**Comment by jrands** [comment]
sites table now has a foreign key constraint on addresses as of 45a75c50aaa9c951fd6e5c771e7b465815d6e5f8. If the UI team ends up doing that the DB supports it.
