### ISSUE TITLE
createOutOfHouseParticipant error

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Database#93]
Can't submit attendance because of pg_error with creating out of house participant

```SQL
SELECT peopleinsert
(
fname := 'arnold'::text, 
lname := 'palmer'::text, 
minit := ''::varchar 
);
```
-return value of 86

```SQL
SELECT createOutOfHouseParticipant
( 
outOfHouseParticipantId := 86::int,
 participantAge := 25::int,
 participantRace := 'Caucasian'::race,
 eID := 1::int 
);
```

`[2F005] ERROR: control reached end of function without RETURN Where: PL/pgSQL function createoutofhouseparticipant(integer,integer,race,sex,text,integer)`

**Comment by marcosb1** [comment]
should be resolved in b0eb0130005f21f388cfdefb8632ac8fca3338a5

**Comment by Scott123180** [comment]
@marcosb1 @jrands 
Is this deployed on 10.11.12.34?

I got the same error message:
```[2F005] ERROR: control reached end of function without RETURN Where: PL/pgSQL function createoutofhouseparticipant(integer,integer,race,sex,text,integer)```


Code that I ran
```SQL
SELECT peopleinsert
( 
fname := 'arnold'::text, 
lname := 'palmer'::text, 
minit := ''::varchar 
);
```

--return value of 107

```SQL
SELECT createOutOfHouseParticipant
( 
outOfHouseParticipantId := 107::int, 
participantAge := 25::int, 
participantRace := 'Caucasian'::race, 
eID := 1::int
);
```

**Comment by marcosb1** [comment]
Not deployed on `10.11.12.34` yet. Let me talk to Jimmy.

**Comment by marcosb1** [comment]
@Scott123180 I just sourced the function. Can you check again?

**Comment by Scott123180** [comment]
@marcosb1 thanks, I think it works now
